### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [sebastian-stumpf/narfkb#1]
This looks like a great little board! What's the license for the files if I'd like to print my own? 

Thanks for sharing! 
🎩

**Comment by sebastian-stumpf** [comment]
That's a good point. Thank you. I've added the MIT license file here: https://github.com/sebastian-stumpf/narfkb/commit/60071629ff74435773e6028236189e77b4fad2c3

**Comment by BigBlueHat** [comment]
Thanks!
